services:
  telegram-bot:
    build: ./services/telegram-bot/
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

    develop:
      watch:
        - path: ./services/telegram-bot/
          action: rebuild
